### ISSUE TITLE
WAL log samples: log series: write metrics/wal/000315: file already closed

### ISSUE THREAD

**Issue by iksaif** [prometheus/tsdb#317]
This is something that happens when the disk is full. The caller should probably have a proper health check for that, but it's another story(https://github.com/prometheus/prometheus/issues/3283). tsdb should certainly not try to write to an already closed file.

This must come from:
https://github.com/prometheus/tsdb/blob/b7173eb0e5558c720ec4c939af7e803d38aa1cce/wal.go#L763 and the fact that in https://github.com/prometheus/tsdb/blob/b7173eb0e5558c720ec4c939af7e803d38aa1cce/wal.go#L604 the function returns early without setting `cur` to `nil` on failure.

I suspect that we should instead set `cur` to `nil` early in `cut()` and handle this case in `write()`.

cc: @Thib17

**Comment by krasi-georgiev** [comment]
Thanks for the nice pointers. I will check this bug.

**Comment by krasi-georgiev** [comment]
I can't seem to replicate it.

```
fallocate -l 50M disk.img
mkfs disk.img
sudo mount -o loop disk.img ./data
sudo chmod -R 777 data
go run main.go  uname_default.go fdlimits_default.go --config.file=../../promBench.yml
```

<details><summary>prom config</summary>

```
global:
  scrape_interval:     200ms # Set the scrape interval to every 15 seconds. Default is every 1 minute.
 
scrape_configs:
  - job_name: 'master'
    # scrape_interval: 50ms 
    static_configs:
      - targets: ['localhost:9090']
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus1'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'prometheus2'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus3'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'prometheus4'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'prometheus5'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus6'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus7'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus8'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus9'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus10'
    static_configs:
      - targets: ['localhost:9090']
  ```

</details>

```
level=warn ts=2018-04-17T09:14:42.7401957Z caller=scrape.go:706 component="scrape manager" scrape_pool=prometheus7 target=http://localhost:9090/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000002: no space left on device"
level=warn ts=2018-04-17T09:14:42.74177436Z caller=scrape.go:706 component="scrape manager" scrape_pool=prometheus22 target=http://localhost:9090/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000002: no space left on device"
level=warn ts=2018-04-17T09:14:42.75743852Z caller=scrape.go:706 component="scrape manager" scrape_pool=prometheus1 target=http://localhost:9090/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000002: no space left on device"
```

```
cp -R data dataB
sudo umount ./data
cp -R dataB data
```

at this point prometheus starts and works as expected on the disk that has enough disk space.
