### ISSUE TITLE
"unknown series references" after clean shutdown

### ISSUE THREAD

**Issue by brandond** [prometheus/tsdb#590]
Not sure if this is the correct repo or not, but I see other similar issues here so this is where I'm landing it.

I appear to be losing WAL entries every time I stop and restart the Docker container hosting my Prometheus instance:

```
level=warn ts=2019-04-24T18:59:57.853Z caller=main.go:484 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2019-04-24T18:59:57.853Z caller=main.go:509 msg="Stopping scrape discovery manager..."
level=info ts=2019-04-24T18:59:57.853Z caller=main.go:523 msg="Stopping notify discovery manager..."
level=info ts=2019-04-24T18:59:57.853Z caller=main.go:545 msg="Stopping scrape manager..."
level=info ts=2019-04-24T18:59:57.853Z caller=main.go:505 msg="Scrape discovery manager stopped"
level=info ts=2019-04-24T18:59:57.853Z caller=main.go:519 msg="Notify discovery manager stopped"
level=info ts=2019-04-24T18:59:57.853Z caller=manager.go:743 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-04-24T18:59:57.853Z caller=manager.go:749 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-04-24T18:59:57.853Z caller=main.go:539 msg="Scrape manager stopped"
level=info ts=2019-04-24T18:59:57.855Z caller=notifier.go:522 component=notifier msg="Stopping notification manager..."
level=info ts=2019-04-24T18:59:57.855Z caller=main.go:708 msg="Notifier manager stopped"
level=info ts=2019-04-24T18:59:57.856Z caller=main.go:720 msg="See you next time!"
level=info ts=2019-04-24T19:00:17.404Z caller=main.go:285 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2019-04-24T19:00:17.405Z caller=main.go:321 msg="Starting Prometheus" version="(version=2.9.1, branch=HEAD, revision=ad71f2785fc321092948e33706b04f3150eee44f)"
level=info ts=2019-04-24T19:00:17.405Z caller=main.go:322 build_context="(go=go1.12.4, user=root@09f919068df4, date=20190416-17:50:04)"
level=info ts=2019-04-24T19:00:17.405Z caller=main.go:323 host_details="(Linux 4.19.5-1.el7.elrepo.x86_64 #1 SMP Tue Nov 27 12:40:57 EST 2018 x86_64 0c4a5a73b681 (none))"
level=info ts=2019-04-24T19:00:17.405Z caller=main.go:324 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-04-24T19:00:17.405Z caller=main.go:325 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-04-24T19:00:17.405Z caller=main.go:640 msg="Starting TSDB ..."
level=info ts=2019-04-24T19:00:17.406Z caller=web.go:416 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555494135732 maxt=1555524000000 ulid=01D8PREH4BR5WJXRJSAA0XMZVA
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555524000000 maxt=1555588800000 ulid=01D8RFCB5Z1VBTZVCS14P9DA1K
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555588800000 maxt=1555653600000 ulid=01D8TD5WE8SG18D16FQTGVNVW3
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555653600000 maxt=1555718400000 ulid=01D8WAZDNWJTZDZZ70KJN2B05C
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555718400000 maxt=1555783200000 ulid=01D8Y8RYYB2KE5FPVD1X0KERXD
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555783200000 maxt=1555812000000 ulid=01D93ME45939HY4G2C4XF5WJXS
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555956000000 maxt=1555977600000 ulid=01D9425JM8XMBBSE291CZVDGAT
level=info ts=2019-04-24T19:00:17.406Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1555977600000 maxt=1556042400000 ulid=01D95ZZ3Y4FDRWHVWAFKF5M7S1
level=info ts=2019-04-24T19:00:17.407Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556107200000 maxt=1556114400000 ulid=01D97XRN27P3EE07STR5W2MXJ3
level=info ts=2019-04-24T19:00:17.407Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556042400000 maxt=1556107200000 ulid=01D97XRN6R3JNC8JGTY9WED8E9
level=info ts=2019-04-24T19:00:17.407Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556114400000 maxt=1556121600000 ulid=01D984MCAQH4JTDSFHFHV72Y25
level=warn ts=2019-04-24T19:00:19.091Z caller=head.go:454 component=tsdb msg="unknown series references" count=966693
level=info ts=2019-04-24T19:00:19.096Z caller=main.go:655 msg="TSDB started"
level=info ts=2019-04-24T19:00:19.096Z caller=main.go:724 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-04-24T19:00:19.097Z caller=main.go:751 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-04-24T19:00:19.097Z caller=main.go:609 msg="Server is ready to receive web requests."
```

**Comment by brian-brazil** [comment]
You're already on 2.9.1, so wipe the WAL and see if this is still happening.

**Comment by brandond** [comment]
This container was created on 2.9.1 with an empty store volume and has been running for less than a week. Is nuking the WAL still worthwhile, or is there anything else I should try?

**Comment by brian-brazil** [comment]
That's unexpected, that issue is meant to be fixed in that version. Can you share enough of the WAL to reproduce?

**Comment by brandond** [comment]
Sure; should I just grab the tsdb directory while it's running, or shut it down first?

**Comment by brian-brazil** [comment]
Either works.

**Comment by michaelarnauts** [comment]
Could this issue be the same, or is related? https://github.com/prometheus/prometheus/issues/3632

**Comment by michaelarnauts** [comment]
Allright. I will continue here. I have the issue that on every restart, prometheus would forget the last two hours.

By reading this thread, it seems that the wal folder was the issue. I've now moved aside the folder, and tried to restart prometheus, and it seems to pick up recent metrics again (but the missed metrics are gone). It seems that somehow, these wal files are blocking prometheus from recovering or something.

On the error, I could see the following:
```
level=warn ts=2019-05-07T08:45:50.757Z caller=main.go:484 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2019-05-07T08:45:50.757Z caller=main.go:509 msg="Stopping scrape discovery manager..."
level=info ts=2019-05-07T08:45:50.757Z caller=main.go:523 msg="Stopping notify discovery manager..."
level=info ts=2019-05-07T08:45:50.757Z caller=main.go:545 msg="Stopping scrape manager..."
level=info ts=2019-05-07T08:45:50.757Z caller=main.go:505 msg="Scrape discovery manager stopped"
level=info ts=2019-05-07T08:45:50.757Z caller=main.go:519 msg="Notify discovery manager stopped"
level=info ts=2019-05-07T08:45:50.758Z caller=manager.go:743 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-05-07T08:45:50.758Z caller=manager.go:749 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-05-07T08:45:50.758Z caller=main.go:539 msg="Scrape manager stopped"
level=info ts=2019-05-07T08:45:50.770Z caller=notifier.go:527 component=notifier msg="Stopping notification manager..."
level=info ts=2019-05-07T08:45:50.770Z caller=main.go:708 msg="Notifier manager stopped"
level=info ts=2019-05-07T08:45:50.770Z caller=main.go:720 msg="See you next time!"
level=info ts=2019-05-07T08:45:52.153Z caller=main.go:285 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2019-05-07T08:45:52.153Z caller=main.go:321 msg="Starting Prometheus" version="(version=2.9.2, branch=HEAD, revision=d3245f15022551c6fc8281766ea62db4d71e2747)"
level=info ts=2019-05-07T08:45:52.153Z caller=main.go:322 build_context="(go=go1.12.4, user=root@1d43b6951e8f, date=20190424-15:32:31)"
level=info ts=2019-05-07T08:45:52.154Z caller=main.go:323 host_details="(Linux 4.15.18-13-pve #1 SMP PVE 4.15.18-37 (Sat, 13 Apr 2019 21:09:15 +0200) x86_64 64ded187259c (none))"
level=info ts=2019-05-07T08:45:52.154Z caller=main.go:324 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-05-07T08:45:52.154Z caller=main.go:325 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-05-07T08:45:52.155Z caller=main.go:640 msg="Starting TSDB ..."
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556708952245 maxt=1556755200000 ulid=01D9VEKZAK2HHYYXES00839ZB6
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556755200000 maxt=1556820000000 ulid=01D9X5HSHKJ5S34QPJT5AAZREQ
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556820000000 maxt=1556884800000 ulid=01D9Z3BEC4M91WPQ0MNBE5E3J8
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556884800000 maxt=1556949600000 ulid=01DA114ZRPKBMN67ZP6XN2CRRV
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1556949600000 maxt=1557014400000 ulid=01DA2YYGW0SD4FK7QX97JXHA8F
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1557014400000 maxt=1557079200000 ulid=01DA4WR25ZC6AF4QT68NKXH3W5
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1557079200000 maxt=1557144000000 ulid=01DA6THKGEBKGVNVPZRA0YVTDC
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1557144000000 maxt=1557165600000 ulid=01DA7F4RXZM48Y9FZ0Y47W362J
level=info ts=2019-05-07T08:45:52.155Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1557187200000 maxt=1557194400000 ulid=01DA83QYFT9G0H68C4JJ88X6WS
level=info ts=2019-05-07T08:45:52.156Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1557165600000 maxt=1557187200000 ulid=01DA83QYPK23GWT5TSG0BCEG3X
level=info ts=2019-05-07T08:45:52.156Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1557194400000 maxt=1557201600000 ulid=01DA8AKNQT3XF37QTKB14MYFK7
level=info ts=2019-05-07T08:45:52.156Z caller=repair.go:47 component=tsdb msg="found healthy block" mint=1557201600000 maxt=1557208800000 ulid=01DA8HFCZSE3G5VEX9T9VAK429
level=info ts=2019-05-07T08:45:52.158Z caller=web.go:416 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=warn ts=2019-05-07T08:45:53.901Z caller=head.go:454 component=tsdb msg="unknown series references" count=926711
level=info ts=2019-05-07T08:45:53.930Z caller=main.go:655 msg="TSDB started"
level=info ts=2019-05-07T08:45:53.930Z caller=main.go:724 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-05-07T08:45:53.930Z caller=main.go:751 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-05-07T08:45:53.930Z caller=main.go:609 msg="Server is ready to receive web requests."
```

docker-compose config:
```
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus/data:/prometheus
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      TZ: 'Europe/Brussels'
    entrypoint:
    - "/bin/prometheus"
    - "--log.level=info"
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
    - "--web.enable-admin-api"
    ports:
    - 9090:9090
```

**Comment by michaelarnauts** [comment]
@krasi-georgiev what way can I send you my wal folder? it's a tgz of 144MB. I prefer privately, I don't know what data might be in the wal files.

**Comment by brian-brazil** [comment]
Now that you've wiped the WAL, you should not see that again on 2.9.2. If that's not the case let us know.

**Comment by michaelarnauts** [comment]
My problem seems to be fixed indeed by removing my wal files, but 2.9.2 has an issue recovering from those (probably) corrupt wal files, so that would still count as a bug, right?

It should probably display an error that recovery was not possible, and cleanup the corrupt wal files. Now it seems to continue using them, so new metrics will still be unrecoverably after a restart.

**Comment by krasi-georgiev** [comment]
@michaelarnauts yes the wal holds the latest 2h so removing it would cause this data loss.
Please make sure you are using the latest Prom version. I and if it happens again now with a fresh WAL please ping me on IRC (#prometheus-dev krasi-georgiev) to send me that WAL folder.

**Comment by krasi-georgiev** [comment]
@michaelarnauts this error doesn't affect receiving new data and when the 2h window passes Prometheus will delete these WAL files. I think this happened due to incorrect checkpointing of the WAL files.

**Comment by krasi-georgiev** [comment]
here is the relevant fix https://github.com/prometheus/tsdb/pull/577

**Comment by michaelarnauts** [comment]
@krasi-georgiev it's not happening again, for me, this is fixed, but there still is a bug in 2.9.2 that caused this.

I've only used 2.9.2, and somehow something went wrong and prometheus wasn't able to recover from this, because everytime I would restart it, it would lose the last two hours.

**Comment by krasi-georgiev** [comment]
@michaelarnauts hm , just to confirm the WAL corruption happened while you were running 2.9.2? If that is the case please ping me on IRC so you can send me that WAL folder if you haven't deleted it yet.

@brandond how is looking on your end? can you please confirm if you noticed anything unusual while running on a fresh WAL folder with 2.9.2?

**Comment by brian-brazil** [comment]
Can you indicate if you're using the delete API?

**Comment by michaelarnauts** [comment]
I have not. Just grafana querying.

**Comment by krasi-georgiev** [comment]
@michaelarnauts can you try to work out steps to reproduce this as we can't figure out yet what might cause this.

**Comment by brian-brazil** [comment]
Can you give us an idea of how many times Prometheus restarts before this happens?

**Comment by michaelarnauts** [comment]
I'm not sure how to reproduce this. I have only used a few node exporters and grafana to graph them out.

@brian-brazil Prometheus doesn't restart. I restarted it myself (since I added a host to the config file). Somehow, something went wrong and the wal files got corrupted. 

ASCII-art that might make it more clear:
```
00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23  -> timeline
-----------------------------------------------------------------------
| 00:00 Prometheus is running fine and capturing metrics.
XX XX XX XX XX
              | 05:00 I restart Prometheus at since I added a new host
XX XX XX -- --|XX XX XX XX
                          | 09:00 I restart prometheus again
XX XX XX -- --|XX XX -- --|XX XX XX XX XX

XX = Metrics are fetched fine
-- = Missing metrics
|  = Restart of prometheus
```

So every time I restart prometheus, it lost the last 2 hours, but everything else is kept. This seem to me that the wal files were somehow corrupted and not cleared on the 2-hour mark when the wal files were compacted to the other db files.

**Comment by brian-brazil** [comment]
So a single restart was sufficient from the first every start from that data directory, and the data affected was across the entire 2h head?

**Comment by michaelarnauts** [comment]
Hmm, I guess it didn't start after the first restart when I started using Prometheus. I assume a crash or unclean shutdown happened to trigger the corruption.

**Comment by brian-brazil** [comment]
So 2 restarts then. This is a code bug, not a corruption. Just need to figure out what's causing it.

**Comment by brandond** [comment]
I have been seeing the same thing - it's always one of the most recent two-hour-periods that's corrupted when I restart. Not the current period that's being written to the WAL, but the one that should have just been compacted. Additionally, not all series in that period are lost, just some of them.

**Comment by eminence** [comment]
I am also seeing this, running 2.9.2.  I don't know if this matters, but I'm running prometheus in a docker container with a docker volume to a host NFS share.

**Comment by brian-brazil** [comment]
Have you noticed if the series would have started/ended always at a similar 2-hour period?

Using NFS is not supported, but not the issue here.

**Comment by eminence** [comment]
Actually it seems to be a 3-hour period of data that's missing.  But the missing data is only for a few series (I'm not sure if this is coincidence, but all the missing series are from the same scrape target)

**Comment by brian-brazil** [comment]
Interesting. Is these churn in those metrics, is it all of that target, what's the lifecycle of that target like?

**Comment by brandond** [comment]
I have a static list of 6 hosts collecting from the node exporter plus two different app exporters. The labels within those metrics don't change much at all.

Mine are Docker on local disk (SSD; dev workstation)

**Comment by eminence** [comment]
> Is these churn in those metrics, is it all of that target, what's the lifecycle of that target like?

By coincidence I did introduce some churn around this time by updating my exporter to not report stats that are stale.  So here's what the data looks like now:

![image](https://user-images.githubusercontent.com/402454/58118910-d7c57700-7bcf-11e9-9de7-70b993a73a2a.png)


Every series in this target went missing for this same time period.  The target is declared as a static config, with a collection interval of 15 seconds.

**Comment by brian-brazil** [comment]
> I have a static list of 6 hosts collecting from the node exporter plus two different app exporters. The labels within those metrics don't change much at all.

So to be clear, completely existing time series?

**Comment by WestonAGreene** [comment]
I was experiencing this same issue (every restart would lose the last two hours of data).
Turned out I needed to use the default storage location: /data

My openshift container yaml:
```
            - name: ${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}
              image: prom/prometheus
              args:
                - '--config.file=/etc/${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}/${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}.yaml'
                # - '--storage.tsdb.path=/${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}'  # 
                - '--storage.tsdb.path=/data'  # prometheus continually was losing it's last two hours of timeseries for every restart. I was afraid this was due to my unique file location. /data is the default https://github.com/prometheus/tsdb/issues/590
                - '--web.external-url=http://localhost:19090/'  # (https://www.robustperception.io/adding-basic-auth-to-prometheus-with-nginx)
                - '--web.route-prefix=/'
                - '--web.enable-lifecycle'  # https://www.robustperception.io/reloading-prometheus-configuration
              imagePullPolicy: Always
              resources:
                limits:
                  memory: ${PROMETHEUS_MEMORY} # setting requests because I think the grafana UI is slow because it doesn't have enough processing  # didn't fix the problem. 2019-05-22_17.10
                  cpu: ${CPU}
              ports:
                - containerPort: 9090
                  protocol: TCP
              # livenessProbe:  # continually fails
              #   tcpSocket:
              #     port: 9090
              volumeMounts:
                - name: ${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}-yaml
                  mountPath: /etc/${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}
                - name: ${PROMETHEUS_APP_NAME}-rules-yaml
                  mountPath: /rules/
                - name: ${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}-pvc
                  # mountPath: /${PROMETHEUS_APP_NAME}${APP_NAME_FLAG_A}
                  mountPath: /data
```

Using prometheus version 2.9.2
